export const FETCH_DATA_REQUEST ="FETCH_DATA_REQUEST"
export const FETCH_DATA_SUCESS ="FETCH_DATA_SUCESS"
export const FETCH_DATA_FAILD ="FETCH_DATA_FAILD"

export const FETCH_DETAIL_REQUEST ="FETCH_DETAIL_REQUEST"
export const FETCH_DETAIL_SUCESS ="FETCH_DETAIL_SUCESS"
export const FETCH_DETAIL_FAILD ="FETCH_DETAIL_FAILD"